[agent]
  interval = "5s"
  round_interval = true

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "k6"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  container_name_include = ["mudda-app-1", "mudda-db-1"]
  timeout = "5s"
