# ========== PostgreSQL Configuration ==========
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

# Hibernate JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Uncomment to generate SQL performance statistics
#spring.jpa.properties.hibernate.generate_statistics=true

# ========== Server ==========
server.port=8080
server.tomcat.connection-timeout=10s
#TODO: improve timeout handling
server.error.include-stacktrace=always

# ========== Unauthenticated Spring Security ==========
spring.security.user.name=root
spring.security.user.password=root

# ========== Amazon S3 Bucket ==========
amazon.s3.bucket-name=test
amazon.s3.region=ap-south-1
amazon.s3.access-key=test
amazon.s3.secret-key=test
spring.cloud.aws.endpoint=http://localhost:4566

# ========== Security ==========
security.jwt.secret-key=dGVzdC1qd3Qtc2VjcmV0LWtleS0zMmJ5dGVzLWxvbmcxMjM0NTY=
security.jwt.access-ttl-min=1440
security.jwt.refresh-ttl-days=15

# ========== Mail ==========
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=sigma
spring.mail.password=sigma

# ========== App ==========
app.frontend-base-url=http://localhost:8080
app.cors.allowed-origins=https://www.mudda.dev,http://mudda-frontend.vercel.app,http://localhost:3000

app.session.key=dGVzdC1qd3Qtc2VjcmV0LWtleS0zMmJ5dGVzLWxvbmcxMjM0NTY=
