# ========== PostgreSQL Configuration ==========
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

# Hibernate JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Don't know what these below do so commented
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.properties.hibernate.generate_statistics=true

# ========== Server ==========
server.port=8080
server.tomcat.connection-timeout=10s
#TODO: improve timeout handling
server.error.include-stacktrace=always

# ========== Logging ==========
logging.level.org.springframework=debug
logging.level.org.springframework.security=debug
logging.level.com.mudda=debug
logging.file.path=logs
logging.file.name=logs/mudda.log

# ========== Unauthenticated Spring Security ==========
spring.security.user.name=root
spring.security.user.password=root

# ========== Amazon S3 Bucket ==========
amazon.s3.bucket-name=${AWS_BUCKET_NAME}
amazon.s3.region=${AWS_REGION}
amazon.s3.access-key=${AWS_ACCESS_KEY_ID}
amazon.s3.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.java.v1.printLocation=false
aws.java.v1.disableDeprecationAnnouncement=true

# ========== Security ==========
security.jwt.secret-key=25-din-me-paisa-double-true-scheme-fr-chat
security.jwt.access-ttl-min=1440
security.jwt.refresh-ttl-days=15

# ========== Mail ==========
spring.mail.host=${MAIL_PROVIDER:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:sigma}
spring.mail.password=${MAIL_PASSWORD:sigma}

# ========== App ==========
app.frontend-base-url=http://localhost:3000

app.rate-limit.auth-capacity=20
app.rate-limit.auth-refill-tokens=10
app.rate-limit.auth-refill-minutes=1

app.cors.allowed-origins=https://www.mudda.dev,http://mudda-frontend.vercel.app,http://localhost:3000
app.cdn.origin=https://cdn.mudda.dev/

app.session.key=hattori-hattori-ye-hai-apna-yaar
