spring.application.name=backend
spring.profiles.active=dev

# ========== PostgreSQL Configuration ==========
spring.datasource.driver-class-name=org.postgresql.Driver

# Logging Messages configuration
spring.messages.basename=messages

app.email.verify-path=/auth/verify-email/confirm
app.email.reset-path=/auth/reset-password
app.email.retry.max-attempts=3
app.email.retry.backoff-ms=2000

# ========== App ==========
app.cdn.origin=https://cdn.mudda.dev/

app.token.resend-cooldown-minutes=5
app.token.verification-expiry-hours=24

app.security.login.max-attempts=5
app.security.login.lock-duration-minutes=15

# Upload Limits
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=10MB

# Mail Protocol Defaults
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Spring Cloud AWS Config
spring.cloud.aws.region.static=${AWS_REGION}

# SQS Config
#spring.cloud.aws.sqs.endpoint=https://sqs.ap-south-1.amazonaws.com/878126142459/
#spring.cloud.aws.sqs.queue-not-found-strategy=fail
spring.cloud.aws.sqs.queue-not-found-strategy=fail
